

const SCREENS = {
  LoginScreen: "LoginScreen",
  RegisterScreen: "RegisterScreen",
  ForgotPasswordScreen: "ForgotPasswordScreen",
  ChangePasswordScreen: "ChangePasswordScreen",
  SignUpScreen: "SignUpScreen",
  Home: "Home",
  MainDrawer: "MainDrawer",
  NavBar: "NavBar",
  ScoreCard: "ScoreCard",
  MatchScoreCard: "MatchScoreCard",
  CreateTournament: "CreateTournament",
  CreateTeam: "CreateTeam",
  CreateMatch: "CreateMatch",
  MyCricket: "MyCricket",
  TeamProfile: "TeamProfile",
  EditTeam: "EditTeam",
  TournamentProfile: "TournamentProfile",
  EditTournament: "EditTournament",
  AddPlayer: "AddPlayer",
  SelectSquadScreen: "SelectSquadScreen",
  SelectTeamScreen: "SelectTeamScreen",
  MatchDetailsScreen: "MatchDetailsScreen",
  TossScreen: "TossScreen",
  PlayerSelectionScreen: "PlayerSelectionScreen",
  ScorerScreen: "ScorerScreen",
  PlayerProfile: "PlayerProfile",
  EditPlayerProfile: "EditPlayerProfile",
  MyQR: "MyQR",
  BlogList: "BlogList",
  BlogPost: "BlogPost",
  Settings: "Settings",
  AllTournaments: "AllTournaments",
  SearchScreen: "SearchScreen",
  ChangeSquad: "ChangeSquad",
  ChangeBowler: "ChangeBowler",
  ThemeConfig: "ThemeConfig",
  GoLiveSetup: "GoLiveSetup",
  AllMatches: "AllMatches",
  ChangePassword: "ChangePassword",
  HomeConfig: "HomeConfig",
  SetupAds: "SetupAds",
  BlogPosts: "BlogPosts",
  QRScanner: "QRScanner",
  TournamentUpgrade: "TournamentUpgrade",
  PlayerRankings: "PlayerRankings",
  CompleteProfile: "CompleteProfile",
};

export default SCREENS;