// utils/locationsData.js
// Comprehensive hierarchical location data for Country -> State -> District filtering

export const COUNTRIES = [
  { id: "India", name: "India", flag: "🇮🇳" },
];

export const STATES_BY_COUNTRY = {
  India: [
    "Haryana",
    "Delhi",
    "Punjab",
    "Rajasthan",
    "Uttar Pradesh",
    "Maharashtra",
    "Gujarat",
    "Karnataka",
    "Madhya Pradesh",
    "Bihar",
    "West Bengal",
    "Tamil Nadu",
    "Telangana",
    "Andhra Pradesh",
    "Kerala",
    "Himachal Pradesh",
    "Uttarakhand",
    "Jammu and Kashmir",
    "Chandigarh",
    "Goa",
    "Assam",
    "Odisha",
    "Jharkhand",
    "Chhattisgarh",
    "Puducherry",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Sikkim",
    "Tripura",
    "Arunachal Pradesh",
    "Ladakh",
  ],
};

export const DISTRICTS_BY_STATE = {
  Haryana: [
    "Hisar",
    "Rohtak",
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Ambala",
    "Karnal",
    "Sonipat",
    "Sirsa",
    "Bhiwani",
    "Jind",
    "Fatehabad",
    "Yamunanagar",
    "Kurukshetra",
    "Kaithal",
    "Rewari",
    "Palwal",
    "Jhajjar",
    "Charkhi Dadri",
    "Mahendragarh",
    "Nuh",
    "Panchkula",
  ],
  Delhi: [
    "New Delhi",
    "Central Delhi",
    "East Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "Shahdara",
    "South Delhi",
    "South East Delhi",
    "South West Delhi",
    "West Delhi",
  ],
  Punjab: [
    "Amritsar",
    "Ludhiana",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali (SAS Nagar)",
    "Hoshiarpur",
    "Gurdaspur",
    "Firozpur",
    "Kapurthala",
    "Sangrur",
    "Pathankot",
    "Moga",
    "Fazilka",
    "Mansa",
    "Barnala",
    "Muktsar",
    "Faridkot",
    "Fatehgarh Sahib",
    "Rupnagar (Ropar)",
    "Tarn Taran",
    "Malerkotla",
  ],
  Rajasthan: [
    "Jaipur",
    "Jodhpur",
    "Udaipur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Alwar",
    "Sikar",
    "Bhilwara",
    "Sri Ganganagar",
    "Bharatpur",
    "Pali",
    "Chittorgarh",
    "Jhunjhunu",
    "Hanumangarh",
    "Barmer",
    "Nagaur",
    "Churu",
    "Dausa",
    "Tonk",
  ],
  "Uttar Pradesh": [
    "Lucknow",
    "Noida (Gautam Buddha Nagar)",
    "Ghaziabad",
    "Kanpur",
    "Varanasi",
    "Agra",
    "Meerut",
    "Prayagraj",
    "Aligarh",
    "Bareilly",
    "Moradabad",
    "Gorakhpur",
    "Saharanpur",
    "Mathura",
    "Ayodhya",
    "Jhansi",
    "Muzaffarnagar",
    "Firozabad",
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Chhatrapati Sambhajinagar (Aurangabad)",
    "Solapur",
    "Kolhapur",
    "Navi Mumbai",
    "Amravati",
    "Jalgaon",
    "Nanded",
    "Sangli",
    "Satara",
    "Ahmednagar",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Gandhinagar",
    "Junagadh",
    "Anand",
    "Mehsana",
    "Kutch",
    "Bharuch",
  ],
  Karnataka: [
    "Bengaluru Urban",
    "Bengaluru Rural",
    "Mysuru",
    "Hubballi-Dharwad",
    "Mangaluru",
    "Belagavi",
    "Kalaburagi",
    "Davanagere",
    "Ballari",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
  ],
  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Gwalior",
    "Jabalpur",
    "Ujjain",
    "Sagar",
    "Rewa",
    "Satna",
    "Ratlam",
    "Dewas",
    "Chhindwara",
  ],
  Bihar: [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Purnia",
    "Darbhanga",
    "Bihar Sharif",
    "Arrah",
    "Begusarai",
    "Katihar",
  ],
  "West Bengal": [
    "Kolkata",
    "North 24 Parganas",
    "South 24 Parganas",
    "Howrah",
    "Durgapur",
    "Asansol",
    "Siliguri",
    "Hooghly",
    "Nadia",
    "Purba Medinipur",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Tiruppur",
    "Vellore",
    "Erode",
    "Thanjavur",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Karimnagar",
    "Khammam",
    "Ranga Reddy",
    "Medchal-Malkajgiri",
    "Sangareddy",
  ],
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Kakinada",
    "Rajahmundry",
    "Tirupati",
    "Anantapur",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Ernakulam (Kochi)",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Kannur",
    "Palakkad",
    "Malappuram",
    "Alappuzha",
    "Kottayam",
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Kangra (Dharamshala)",
    "Mandi",
    "Solan",
    "Kullu",
    "Hamirpur",
    "Una",
    "Bilaspur",
    "Sirmaur",
    "Chamba",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Nainital (Haldwani)",
    "Udham Singh Nagar (Rudrapur)",
    "Rishikesh",
    "Pauri Garhwal",
    "Almora",
  ],
  "Jammu and Kashmir": [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Udhampur",
    "Kathua",
    "Budgam",
    "Pulwama",
  ],
  Chandigarh: [
    "Chandigarh",
  ],
  Goa: [
    "North Goa",
    "South Goa",
    "Panaji",
    "Margao",
  ],
};

export const getCountries = () => COUNTRIES;

export const getStatesForCountry = (country = "India") => {
  return STATES_BY_COUNTRY[country] || STATES_BY_COUNTRY.India || [];
};

export const getDistrictsForState = (state) => {
  if (!state) return [];
  const list = DISTRICTS_BY_STATE[state];
  if (list && list.length > 0) return list;
  return [];
};
